package com.iconpackdumper;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.*;import android.content.res.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.provider.MediaStore;import android.util.Xml;import android.view.*;import android.widget.*;import androidx.appcompat.app.*;import androidx.core.view.*;import com.google.android.material.color.DynamicColors;import com.google.android.material.dialog.MaterialAlertDialogBuilder;import com.google.android.material.card.MaterialCardView;import com.google.android.material.textfield.TextInputEditText;import java.io.*;import java.util.*;import java.util.zip.*;import org.xmlpull.v1.*;

public class MainActivity extends AppCompatActivity{
 LinearLayout list;TextView status;TextInputEditText search;PackageManager pm;ArrayList<Pack>packs=new ArrayList<>();Pack selected;ArrayList<IconItem>icons=new ArrayList<>();
 static class Pack{String pkg,name;Pack(String p,String n){pkg=p;name=n;}} static class IconItem{String name,drawable;Drawable image;IconItem(String n,String d,Drawable i){name=n;drawable=d;image=i;}}
 @Override public void onCreate(Bundle b){applyTheme();super.onCreate(b);setContentView(R.layout.activity_main);setupBars();pm=getPackageManager();list=findViewById(R.id.list);status=findViewById(R.id.status);search=findViewById(R.id.search);search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){renderIcons(s.toString());}public void afterTextChanged(android.text.Editable e){}});findViewById(R.id.toolbar).setOnClickListener(v->themeMenu());loadPacks();}
 void applyTheme(){if("system".equals(getSharedPreferences("prefs",0).getString("theme","system")))DynamicColors.applyToActivityIfAvailable(this);}
 void setupBars(){WindowCompat.setDecorFitsSystemWindows(getWindow(),false);int bar=getSharedPreferences("prefs",0).getInt("bar",0);boolean light=bar==1|| (bar==0&&(getResources().getConfiguration().uiMode&android.content.res.Configuration.UI_MODE_NIGHT_MASK)!=android.content.res.Configuration.UI_MODE_NIGHT_YES);WindowInsetsControllerCompat c=WindowCompat.getInsetsController(getWindow(),getWindow().getDecorView());c.setAppearanceLightStatusBars(light);c.setAppearanceLightNavigationBars(light);View root=findViewById(R.id.root);ViewCompat.setOnApplyWindowInsetsListener(root,(v,in)->{androidx.core.graphics.Insets x=in.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(x.left,x.top,x.right,x.bottom);return in;});}
 void themeMenu(){String[]x={"System Monet (recommended)","Status bar: black icons","Status bar: white icons","Dump installed apps"};new MaterialAlertDialogBuilder(this).setTitle("Display settings / dump").setItems(x,(d,w)->{if(w<3){getSharedPreferences("prefs",0).edit().putString("theme",w==0?"system":"fixed").putInt("bar",w).apply();if(w==0)DynamicColors.applyToActivityIfAvailable(this);recreate();}else loadInstalledApps();}).show();}
 void loadPacks(){new Thread(()->{LinkedHashMap<String,Pack>m=new LinkedHashMap<>();String[]actions={"com.novalauncher.THEME","app.lawnchair.icons.THEMED_ICON","ch.deletescape.lawnchair.ICONPACK","org.adw.launcher.THEMES","com.anddoes.launcher.THEME","com.gau.go.launcherex.theme","ginlemon.smartlauncher.THEMES"};for(String a:actions)for(ResolveInfo x:pm.queryIntentActivities(new Intent(a),PackageManager.MATCH_ALL)){String p=x.activityInfo.packageName;if(!p.equals(getPackageName()))m.put(p,new Pack(p,pm.getApplicationLabel(x.activityInfo.applicationInfo).toString()));}for(ApplicationInfo a:pm.getInstalledApplications(0))if(!a.packageName.equals(getPackageName())&&hasFilter(a))m.put(a.packageName,new Pack(a.packageName,pm.getApplicationLabel(a).toString()));ArrayList<Pack>r=new ArrayList<>(m.values());runOnUiThread(()->{packs=r;status.setText(r.size()+" Nova-compatible icon packs");renderPacks();});}).start();}
 boolean hasFilter(ApplicationInfo a){try{Resources r=pm.getResourcesForApplication(a);return r.getIdentifier("appfilter","xml",a.packageName)!=0||r.getIdentifier("appfilter","raw",a.packageName)!=0||zipHas(a.sourceDir,"assets/appfilter.xml");}catch(Exception e){return false;}}
 boolean zipHas(String path,String n){try{ZipFile z=new ZipFile(path);boolean b=z.getEntry(n)!=null;z.close();return b;}catch(Exception e){return false;}}
 void renderPacks(){list.removeAllViews();for(Pack p:packs){MaterialCardView card=new MaterialCardView(this);card.setUseCompatPadding(true);TextView t=new TextView(this);t.setText(p.name+"\n"+p.pkg);t.setTextSize(16);t.setPadding(24,20,24,20);card.addView(t);card.setOnClickListener(v->{selected=p;loadIcons(p);});list.addView(card);}}
 void loadIcons(Pack p){status.setText("Loading icons…");new Thread(()->{ArrayList<IconItem>r=parse(p);runOnUiThread(()->{icons=r;status.setText(p.name+": "+r.size()+" icons (long-press to save)");renderIcons("");});}).start();}
 ArrayList<IconItem>parse(Pack p){ArrayList<IconItem>r=new ArrayList<>();try{ApplicationInfo a=pm.getApplicationInfo(p.pkg,0);Resources res=pm.getResourcesForApplication(a);parseNamed(p,a,res,"appfilter",r);parseNamed(p,a,res,"drawable",r);}catch(Exception ignored){}return r;}
 void parseNamed(Pack p,ApplicationInfo a,Resources res,String name,ArrayList<IconItem>r)throws Exception{int id=res.getIdentifier(name,"xml",p.pkg);if(id!=0){parseXml(res.getXml(id),res,p.pkg,r);return;}id=res.getIdentifier(name,"raw",p.pkg);if(id!=0){InputStream in=res.openRawResource(id);XmlPullParser x=Xml.newPullParser();x.setInput(in,"UTF-8");parseXml(x,res,p.pkg,r);in.close();return;}ZipFile z=new ZipFile(a.sourceDir);String[]paths={"assets/"+name+".xml","res/xml/"+name+".xml"};for(String path:paths){ZipEntry e=z.getEntry(path);if(e!=null){InputStream in=z.getInputStream(e);XmlPullParser x=Xml.newPullParser();x.setInput(in,"UTF-8");parseXml(x,res,p.pkg,r);in.close();break;}}z.close();}
 ArrayList<IconItem>parseXml(XmlPullParser x,Resources res,String pkg,ArrayList<IconItem>r)throws Exception{while(x.next()!=XmlPullParser.END_DOCUMENT){if(x.getEventType()==XmlPullParser.START_TAG&&(x.getName().equals("item")||x.getName().equals("calendar"))){String comp=x.getAttributeValue(null,"component"),d=x.getAttributeValue(null,"drawable");if(d==null)d=x.getAttributeValue(null,"prefix");if(d!=null){int id=res.getIdentifier(d,"drawable",pkg);if(id==0)id=res.getIdentifier(d,"mipmap",pkg);if(id!=0&&!containsDrawable(r,d))r.add(new IconItem(comp==null?d:comp,d,res.getDrawable(id,getTheme())));}}}return r;}
 boolean containsDrawable(ArrayList<IconItem>r,String d){for(IconItem i:r)if(i.drawable.equals(d))return true;return false;}
 void loadInstalledApps(){new Thread(()->{ArrayList<IconItem>r=new ArrayList<>();for(ApplicationInfo a:pm.getInstalledApplications(0))if(!a.packageName.equals(getPackageName()))r.add(new IconItem(pm.getApplicationLabel(a).toString(),a.packageName,a.loadIcon(pm)));runOnUiThread(()->{selected=new Pack("installed","Installed apps");icons=r;status.setText(r.size()+" apps (long-press to save original icons)");renderIcons("");});}).start();}
 void renderIcons(String q){if(selected==null)return;list.removeAllViews();String z=q.toLowerCase();for(IconItem i:icons){if(!z.isEmpty()&&!i.name.toLowerCase().contains(z)&&!i.drawable.toLowerCase().contains(z))continue;MaterialCardView c=new MaterialCardView(this);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(16,12,16,12);ImageView im=new ImageView(this);im.setImageDrawable(i.image);row.addView(im,new LinearLayout.LayoutParams(72,72));TextView t=new TextView(this);t.setText(i.name+"\n"+i.drawable);t.setPadding(16,0,0,0);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);c.setOnLongClickListener(v->{saveIcon(i);return true;});list.addView(c);}}
 void saveIcon(IconItem i){Bitmap b=Bitmap.createBitmap(256,256,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(b);i.image.setBounds(0,0,256,256);i.image.draw(c);try{ContentValues v=new ContentValues();v.put(MediaStore.Images.Media.DISPLAY_NAME,i.drawable.replaceAll("[^a-zA-Z0-9._-]","_")+".png");v.put(MediaStore.Images.Media.MIME_TYPE,"image/png");v.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/iconpackdumper");Uri u=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,v);OutputStream o=getContentResolver().openOutputStream(u);b.compress(Bitmap.CompressFormat.PNG,100,o);o.close();Toast.makeText(this,"Saved to Pictures/iconpackdumper",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Could not save icon",Toast.LENGTH_SHORT).show();}}
}
